### PR TITLE
fix: react ref

### PR DESCRIPTION
**Pull request by zhigang1992**
Previous method only works with function ref, now it works with React.createRef

### CODE REVIEW

**Comment by Minishlink** [comment]
Can you make a Storybook story showing this please?

**Comment by zhigang1992** [comment]
@Minishlink here you go :)

**Comment by zhigang1992** [comment]
@Minishlink is there anything else I can do to move this forward?

**Comment by xiCO2k** [comment]
@Minishlink Can you please take a look on this? Thanks

**Pull request closed without merging**
